# Generated by Django 2.1.7 on 2019-03-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('id_off', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Categories',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_places', models.CharField(max_length=255)),
                ('categories_prev_hierarchy', models.CharField(max_length=255)),
                ('product_quantity', models.IntegerField()),
                ('labels_hierarchy', models.CharField(max_length=255)),
                ('quality_tags', models.IntegerField()),
                ('manufacturing_places', models.CharField(max_length=255)),
                ('brands_tags', models.CharField(max_length=255)),
                ('origins', models.CharField(max_length=255)),
                ('additives_prev_original_tags', models.CharField(max_length=255)),
                ('stores_tags', models.CharField(max_length=255)),
                ('emb_codes_tags', models.IntegerField()),
                ('nova_group', models.IntegerField()),
                ('serving_size', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Description',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('nutrition_grade', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='purebeurre.Category')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='purebeurre.Description')),
            ],
            options={
                'db_table': 'Products',
                'ordering': ['id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_products', to='purebeurre.Product')),
                ('old_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_products', to='purebeurre.Product')),
            ],
            options={
                'db_table': 'Substitutions',
                'ordering': ['id'],
                'managed': True,
            },
        ),
    ]
