# Generated by Django 2.1.7 on 2019-03-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purebeurre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ingredients',
            new_name='toto',
        ),
    ]
