# Generated by Django 2.1.7 on 2019-03-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purebeurre', '0002_auto_20190304_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='toto',
            new_name='ingredients',
        ),
    ]
