# Generated by Django 2.1.7 on 2019-03-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purebeurre', '0003_auto_20190304_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='Pics', max_length=255),
        ),
    ]
